# This is a basic workflow to help you get started with Actions

name: Close Issue

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: 
      - closed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Test Project
          column: Done
          repo-token: ${{ secrets.REPO_PAT }}
